name: Nightly Build

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: '4 0 * * *'

jobs:
  nightly-build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed for GitHub Releases
      actions: write   # Needed for uploading artifacts

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the build script
        run: sudo bash create_image.sh

      - name: Update the nightly release
        uses: softprops/action-gh-release@v1
        with:
          files: p2000t-sd-card.img.zip
          tag_name: nightly
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
